version: '3'

services:
    ansible:
        container_name: ansible
        image: ansible/ansible:ubuntu1404
#        volumes:
 #       - ./keys:/root/.ssh/      
        networks:
            testing_net:
                ipv4_address: 172.28.1.1

    target1:
        container_name: target1
        image: centos:centos8
        tty: true
#        volumes:
#        - ./keys:/root/.ssh/     
        networks:
            testing_net:
                ipv4_address: 172.28.1.2

    target2:
        container_name: target2
        image: centos:centos8
        tty: true
#        volumes:
 #       - ./keys:/root/.ssh/     
        networks:
            testing_net:
                ipv4_address: 172.28.1.3

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16

