apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
#    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
 #   path: //c/Users/temp
    path: /myvol2