apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  #to support internal load balancing
#    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "svcSubnet"  #use this if we want internal load balancer to take private ip from a different subnet,if not provided it will take ip from aks subnet.Make sure aks sp have network contributor access to resource group of	 svcSubnet
#    service.beta.kubernetes.io/azure-load-balancer-resource-group: kubRg  #if public we want to use is in kubRg,netcontributer needed in kubRg. If ip present inside MC_ this entry not needed & already has netcontributer by default.
  name: azure-load-balancer
spec:
#  loadBalancerIP: 20.43.181.227    #needed for static public/private ip,For external(public) loadbalancer: this public ip will not be deleted if svc is deleted.If this entry is not used aks will provision public ip dynamically ,when service is deleted the public ip will also be deleted.
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: azure-load-balancer



#az role assignment create --assignee 1626e3ec-f716-4d03-b8e9-80becb94e10f  --role "Network Contributor" --scope  /subscriptions/563ac70a-e26c-48fd-a47c-8b4c35ef90cf/resourceGroups/myRg

#az network public-ip create  --resource-group myRg    --name pub-01   --sku Standard  --allocation-method static
