apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-task
spec:
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: build-step
      image: maven:3-alpine
      workingDir: $(resources.inputs.source.path)
    #The path key is already predefined and refers to the local path to a resource on the mounted volume   
      command:
        - mvn
        - -B
        - -DskipTests
        - clean
        - package