apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
spec:
  containers:
  - name: app
    image: alpine
    command: ["sleep", "3600"]
    env:
    - name: SOME_VARIABLE
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
