apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn
spec:
  workspaces:
  - name: maven-repo2   #ie.  will mount at /workspace/maven-repo2
  inputs:
    params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      default: ["package"]
    resources:
    - name: source
      type: git
  steps:
    - name: mvn
      image: gcr.io/cloud-builders/mvn
      workingDir: /workspace/source
      command: ["/usr/bin/mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo2.path)
        - "$(inputs.params.GOALS)"
        #   $(workspaces.maven-repo2.path) will resolve to "/workspace/maven-repo2" 
        # if -Dmaven.repo.local=$(workspaces.maven-repo2.path)  argument not provided repos will be downloaded in <localRepository> defined in settings.xml
        #which is not mounted so we have explicitly passed this maven argument 