apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 500Mi
  accessModes:
#    - ReadWriteOnce
    - ReadWriteMany    
