- name: Execute command to display date on web_node1
  hosts: worker
#  vars:
#  - cmd: date 
  tasks:
    - name: Execute a date command
      command: '{{ cmd }}'
      register: shell_result
    - debug:
        var: shell_result.stdout_lines
- name: Execute a command to display hosts file contents on web_node2
  hosts: worker
  tasks:
    - name: Execute a command to display hosts file
      command: cat /etc/hosts
      register: shell_result
    - debug:
        var: shell_result.stdout_lines      
#    - debug: msg="{{ shell_result.stdout }}"
#    - debug: msg="{{ shell_result.stderr }}"



